/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdlib.h> // for NULL
#include "player/player.h"
#include "FFMediaPlayer.h" // for CONVERT_FUN
#define LOG_TAG "native_convert"
#include "pplog.h"

extern CONVERT_FUN convertFun;

/* Header for class com_pplive_meetplayer_MyFormatConverter */

#ifndef _Included_com_pplive_meetplayer_MyFormatConverter
#define _Included_com_pplive_meetplayer_MyFormatConverter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_pplive_meetplayer_MyFormatConverter
 * Method:    Convert
 * Signature: ([B[B)I
 */
JNIEXPORT jint JNICALL Java_com_pplive_meetplayer_util_MyFormatConverter_Convert
  (JNIEnv *env, jclass clazz, jbyteArray in_flv, jint in_size, jbyteArray out_ts)
{
	PPLOGI("Convert()");

	int ret = -1;

	jbyte* flv_data = env->GetByteArrayElements(in_flv, NULL);
	jsize flv_data_size = in_size;//env->GetArrayLength(in_flv);

	jbyte* ts_data = env->GetByteArrayElements(out_ts, NULL);
	jsize ts_data_size = env->GetArrayLength(out_ts);

	PPLOGI("before call my_convert() flv %p %d, ts %p %d", flv_data, flv_data_size, ts_data, ts_data_size);
	bool bRet = convertFun((uint8_t *)flv_data, flv_data_size, (uint8_t *)ts_data, &ts_data_size);
	if (bRet)
		ret = ts_data_size;
	PPLOGI("after call my_convert() %d", ret);

	env->ReleaseByteArrayElements(in_flv, flv_data, 0);
	env->ReleaseByteArrayElements(out_ts, ts_data, 0);
	return ret;
}

#ifdef __cplusplus
}
#endif
#endif