/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pplive_epg_pptv_NativeMedia */

#ifndef _Included_com_pplive_epg_pptv_NativeMedia
#define _Included_com_pplive_epg_pptv_NativeMedia
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_pplive_epg_pptv_NativeMedia
 * Method:    test
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_pplive_epg_pptv_NativeMedia_test
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_pplive_epg_pptv_NativeMedia
 * Method:    Convert
 * Signature: ([BI[BII)I
 */
JNIEXPORT jint JNICALL Java_com_pplive_epg_pptv_NativeMedia_Convert
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
